### PR TITLE
Add descriptions for services offered by twiinIT

### PR DESCRIPTION
**Pull request by pjeanjean**
This adds a first draft for the services offered by the company, displayed on the homepage as a carroussel:
image

### CODE REVIEW

**Comment by adriendelsalle** [comment]
That looks great thanks @pjeanjean !
Maybe we could add some icons to better illustrate those items?
A cad view taken from lab 3D viewer?
CoSApp logo and maybe a link to Gitlab repo?
Some craftsmanship inspired icon?

**Comment by pjeanjean** [comment]
So, replacing the current icons by slightly bigger, more specific ones? That's a good point, I'll see what I can do

**Comment by adriendelsalle** [comment]
Yeah we could also make it bigger and have a dedicated `Gallery` to advertise a bit more what are the products/services?

**Comment by adriendelsalle** [comment]
ping @pjeanjean

**Comment by adriendelsalle** [comment]
@GuyDSP are you OK with that?

**Comment by GuyDSP** [comment]
Ok with that. 
I would like to see it including the modif discussed. Possible to have a screenshot ?

**Comment by pjeanjean** [comment]
So, for now, we decided to keep the current icons and discuss other improvements in another issue.
The only modification in this regard is to make the icons bigger, which looks like this currently:
image

**Comment by adriendelsalle** [comment]
Look great!
I'm not sure the `modeling expertise` is correctly vertically aligned (icon and title), is it?

**Comment by pjeanjean** [comment]
Fixed, ready to merge

**Comment by adriendelsalle** [comment]
LGTM, thanks @pjeanjean !!
@GuyDSP are you ok?

**Comment by GuyDSP** [comment]
@pjeanjean I am ok!

**Review by GuyDSP — APPROVED** [review]
Ok @pjeanjean thanks!

**Pull request merged**
